/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DfFilter {
    }
    interface FilterContainer {
    }
    interface LangContainer {
    }
    interface LangHeader {
    }
    interface LangSearchBar {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilBoilerplate {
    }
}
export interface LangSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLangSearchBarElement;
}
declare global {
    interface HTMLDfFilterElement extends Components.DfFilter, HTMLStencilElement {
    }
    var HTMLDfFilterElement: {
        prototype: HTMLDfFilterElement;
        new (): HTMLDfFilterElement;
    };
    interface HTMLFilterContainerElement extends Components.FilterContainer, HTMLStencilElement {
    }
    var HTMLFilterContainerElement: {
        prototype: HTMLFilterContainerElement;
        new (): HTMLFilterContainerElement;
    };
    interface HTMLLangContainerElement extends Components.LangContainer, HTMLStencilElement {
    }
    var HTMLLangContainerElement: {
        prototype: HTMLLangContainerElement;
        new (): HTMLLangContainerElement;
    };
    interface HTMLLangHeaderElement extends Components.LangHeader, HTMLStencilElement {
    }
    var HTMLLangHeaderElement: {
        prototype: HTMLLangHeaderElement;
        new (): HTMLLangHeaderElement;
    };
    interface HTMLLangSearchBarElement extends Components.LangSearchBar, HTMLStencilElement {
    }
    var HTMLLangSearchBarElement: {
        prototype: HTMLLangSearchBarElement;
        new (): HTMLLangSearchBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilBoilerplateElement extends Components.StencilBoilerplate, HTMLStencilElement {
    }
    var HTMLStencilBoilerplateElement: {
        prototype: HTMLStencilBoilerplateElement;
        new (): HTMLStencilBoilerplateElement;
    };
    interface HTMLElementTagNameMap {
        "df-filter": HTMLDfFilterElement;
        "filter-container": HTMLFilterContainerElement;
        "lang-container": HTMLLangContainerElement;
        "lang-header": HTMLLangHeaderElement;
        "lang-search-bar": HTMLLangSearchBarElement;
        "my-component": HTMLMyComponentElement;
        "stencil-boilerplate": HTMLStencilBoilerplateElement;
    }
}
declare namespace LocalJSX {
    interface DfFilter {
    }
    interface FilterContainer {
    }
    interface LangContainer {
    }
    interface LangHeader {
    }
    interface LangSearchBar {
        "onSearchEntrySubmit"?: (event: LangSearchBarCustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilBoilerplate {
    }
    interface IntrinsicElements {
        "df-filter": DfFilter;
        "filter-container": FilterContainer;
        "lang-container": LangContainer;
        "lang-header": LangHeader;
        "lang-search-bar": LangSearchBar;
        "my-component": MyComponent;
        "stencil-boilerplate": StencilBoilerplate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "df-filter": LocalJSX.DfFilter & JSXBase.HTMLAttributes<HTMLDfFilterElement>;
            "filter-container": LocalJSX.FilterContainer & JSXBase.HTMLAttributes<HTMLFilterContainerElement>;
            "lang-container": LocalJSX.LangContainer & JSXBase.HTMLAttributes<HTMLLangContainerElement>;
            "lang-header": LocalJSX.LangHeader & JSXBase.HTMLAttributes<HTMLLangHeaderElement>;
            "lang-search-bar": LocalJSX.LangSearchBar & JSXBase.HTMLAttributes<HTMLLangSearchBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-boilerplate": LocalJSX.StencilBoilerplate & JSXBase.HTMLAttributes<HTMLStencilBoilerplateElement>;
        }
    }
}
